### ISSUE TITLE
Link in README points to  "Path not found"

### ISSUE THREAD

**Issue by karczex** [pmem/ndctl#120]
This link https://git.kernel.org/cgit/linux/kernel/git/nvdimm/nvdimm.git/tree/Documentation/nvdimm/nvdimm.txt?h=libnvdimm-for-next should be updated.

**Comment by sscargal** [comment]
The correct link is https://git.kernel.org/pub/scm/linux/kernel/git/nvdimm/nvdimm.git/tree/Documentation/nvdimm/nvdimm.txt

**Comment by stellarhopper** [comment]
Ah, the original link broke because libnvdimm-for-next has moved the documentation to the driver-api 'book':

ae4a05027e2f ("docs: nvdimm: add it to the driver-api book")

The master link will also break the next time master moves forward to catch up with that change.
The correct link should be: https://git.kernel.org/pub/scm/linux/kernel/git/nvdimm/nvdimm.git/tree/Documentation/driver-api/nvdimm/nvdimm.rst?h=libnvdimm-for-next

Or indeed we can take the chance to point to the new Sphinx rendered HTML pages:
https://www.kernel.org/doc/html/latest/driver-api/nvdimm/index.html

I'll send a patch - @karczex if you can send me a "Name <email>" I'd be happy to add Reported-by attribution.
