### ISSUE TITLE
Cannot use all pmem

### ISSUE THREAD

**Issue by mcf-rocks** [pmem/ndctl#162]
Brand new server, set all the pmem to app direct and rebooted:
```
$ ipmctl show -memoryresources
 MemoryType   | DDR         | PMemModule   | Total        
==========================================================
 Volatile     | 128.000 GiB | 0.000 GiB    | 128.000 GiB
 AppDirect    | -           | 1008.000 GiB | 1008.000 GiB
 Cache        | 0.000 GiB   | -            | 0.000 GiB
 Inaccessible | 0.000 GiB   | 3.377 GiB    | 3.377 GiB
 Physical     | 128.000 GiB | 1011.377 GiB | 1139.377 GiB
 ```
 Then create namespace, no args, isn't it supposed to use ALL the pmem?
 ```
$ ndctl create-namespace
{
  "dev":"namespace1.0",
  "mode":"fsdax",
  "map":"dev",
  "size":"496.12 GiB (532.71 GB)",
  "uuid":"6d16f61d-8b24-42cb-95a2-411ff8bb0e48",
  "sector_size":512,
  "align":2097152,
  "blockdev":"pmem1"
}
```
But as you can see, it only used half.
So I destroyed the namespace and tried to specify the size:
```
$ ndctl disable-namespace "namespace1.0"
disabled 1 namespace
$ ndctl destroy-namespace "namespace1.0"
destroyed 1 namespace
$ ndctl list
ndctl create-namespace -s 1000G
failed to create namespace: No space left on device
```
Why does it fail? Why did it not create correct sized namespace in the first place.
I'm a total noob, never used pmem before today.

I think it's to do with the underlying regions - there are two, both 500G - but I can't control those.

What I am trying to do is turn all the pmem into a single disk.

**Comment by mcf-rocks** [comment]
I just used mdadm to raid0 the two /dev/pmem devices into one volume... seems to work... still, why can't I make one namespace?

**Comment by sscargal** [comment]
@mcf-rocks I recommend watching my video on provisioning PMem. It'll help understand what's going on. There's also a Quick Start Guide and some User Guides in the resources below:

[Video - Provision Intel® Optane™ DC Persistent Memory in Linux
](https://software.intel.com/content/www/us/en/develop/videos/provisioning-intel-optane-dc-persistent-memory-modules-in-linux.html) 
[Quick Start Guide Part 1: Persistent Memory Provisioning Introduction
](https://software.intel.com/content/www/us/en/develop/articles/qsg-intro-to-provisioning-pmem.html)
[PMem 'Getting Started', User and Install Guides](https://docs.pmem.io/persistent-memory/) 

The reason is that you have a two-socket server where each CPU socket has 50% of the total PMem and DRAM capacity (don't change this!). When you created the AppDirect goal, the platform creates two 'Regions', one per socket, with the local PMem. Namespaces are created within regions, so your `ndctl create-namespace` command only asked for one namespace. `ndctl create-namespace --continue` will have created two namespaces, as would running `ndctl create-namespace` twice. ie, the following are equivalent ways of provisioning PMem.

```
// Option 1
# ndctl create-namespace --continue

// Option 2
# ndctl create-namespace
# ndctl create-namespace

// Option 3 - More explicit
# ndctl create-namespace --region 0 
# ndctl create-namespace --region 1
```

The `ndctl create-namespace -s 1000G` command failed because you requested a namespace size that is larger than the physical capacity of a region. 

Once the namespaces are created, you then create two filesystems, one per /dev/pmem[01] device. While you can use software RAID to stripe or concatenate the two namespaces, you'll find the performance is much lower than using two independent file systems with NUMA aware processes. 

[Using Linux Volume Manager (LVM) with Persistent Memory](https://stevescargall.com/2019/05/21/using-linux-volume-manager-lvm-with-persistent-memory/)
[Storage Redundancy with Intel® Optane™ Persistent Memory Modules
](https://software.intel.com/content/www/us/en/develop/articles/storage-redundancy-with-intel-optane-persistent-memory-modules.html)

**Comment by mcf-rocks** [comment]
thanks - it all makes sense now - the dimms are connected to different CPUs. 

Already tried "joining" using mdadm to create a raid 0 -- terrible performance. (1500MB/s r/w)
I also tried using btrfs -- better (2400MB/s)
But as independent devices -- best (2900MB/s) 

tested with this command: fio --name=randwrite --ioengine=libaio --iodepth=1 --rw=randrw --bs=4m --direct=0 --size=10G --numjobs=4 --runtime=60 --group_reporting

**Comment by hramrach** [comment]
You can map the regions as memory or use software raid to concatenate the devices when using as storage.

It will likely benefit your application performance to run on specific NUMA node and use the device that represents the pmem connected to that node, though.

**Comment by hramrach** [comment]
And there is likely a way to interleave the pmem regions in ndctl itself, too

**Comment by mkatsa** [comment]
This is how my namespaces are configured. 

The output of ndctl list --regions is :

[
  {
    "dev":"region1",
    "size":270582939648,
    "available_size":0,
    "max_available_extent":0,
    "type":"pmem",
    "iset_id":-5142870461217600990,
    "persistence_domain":"memory_controller"
  },
  {
    "dev":"region0",
    "size":270582939648,
    "available_size":0,
    "max_available_extent":0,
    "type":"pmem",
    "iset_id":4507217640984709666,
    "persistence_domain":"memory_controller"
  }
]

The output of ndctl list is :

[
  {
    "dev":"namespace1.0",
    "mode":"fsdax",
    "map":"dev",
    "size":266352984064,
    "uuid":"b51834b5-c042-4e02-911a-d549603b2dc7",
    "sector_size":512,
    "align":2097152,
    "blockdev":"pmem1"
  },
  {
    "dev":"namespace0.0",
    "mode":"fsdax",
    "map":"dev",
    "size":266352984064,
    "uuid":"09fe6be9-fec5-4a82-b8dc-d29c6cd78538",
    "sector_size":512,
    "align":2097152,
    "blockdev":"pmem0"
  }

I try to actually create a name space through ndctl that fully utilizes region0 and region1. I would like to avoid solutions such as RAID. Could you please provide some more info on how this can be done with ndctl?

**Comment by hramrach** [comment]
It looks like the interleaving provided by hardware/BIOS (if any) happens inside a region, and if you have multiple regions you can assign each to different application (if you are running multiple) or use techniques such as software raid to make use of all the memory for one application (with caveats that apply to software raid).

How software raid would interact with DAX is surely an interesting question.

**Comment by sscargal** [comment]
Most Intel x86 platforms are NUMA (Non-Uniform Memory Access) meaning each CPU socket has locally attached memory (DRAM + PMem) but it can access the memory (DRAM & PMem) attached to other CPU sockets over the UPI Interconnect (Ultra Path Interconnect).

There's nothing at the hardware layer that can make a system look like a UMA (Uniform Memory Access), ie: one contiguous flat address space. ndctl can't help you until we get CXL devices where devices are managed by the OS. Even then, it is recommended to use NUMA local configurations (same as today).

I do not recommend using software RAID as it's difficult to control performance. It works with DAX (with some RAID levels), but introduces significant performance penalties. See [Storage Redundancy with Intel® Optane™ Persistent Memory Modules](https://www.intel.com/content/www/us/en/developer/articles/technical/storage-redundancy-with-intel-optane-persistent-memory-modules.html).

It is the responsibility of the application to be NUMA aware and ideally perform memory local (to the socket) memory accesses. This is not specific to PMem, but also for DRAM, High-Bandwidth Memory, Disk IO, Network, etc. Going over the UPI to access remote data adds ~170ns-300ns which is the UPI latency on a 2-socket system. There's a lot of additional work that the hardware had to do for non-local memory accesses, so non-NUMA apps can cause their own performance issues and leave a lot of performance on the table. 

**If** your motherboard supports a non-symmetric population, you could move the PMem to a single socket, but then you're limiting the number of CPUs your app should use to that socket.
