### ISSUE TITLE
where is "ccan/array_size/array_size.h" in ndctl-devel

### ISSUE THREAD

**Issue by mrpre** [pmem/ndctl#169]
I  installed development component by using `yum install ndctl-devel ndctl-libs` on Centos. When I try to include header file by `#include <ndctl/ndctl.h>`  then I find the "ccan/array_size/array_size.h" is missed.
```
#ifndef __NDCTL_H__
#define __NDCTL_H__

#ifndef ARRAY_SIZE
#include <ccan/array_size/array_size.h>
#endif
#include <linux/types.h>
#include <sys/user.h>
#include <unistd.h>
```

**Comment by djbw** [comment]
ndctl.h is not part of the exported api from libndctl.h which is why it is not enabled via the -devel packages.

That said if you want to retrieve that header file it is available via the ccan project here:
https://github.com/rustyrussell/ccan
https://github.com/rustyrussell/ccan/tree/master/ccan/array_size
