### ISSUE TITLE
make rpm failed

### ISSUE THREAD

**Issue by pokitpeng** [pmem/ndctl#172]
When I tried to build the RPM package on Centos7, I encountered an error. I don't know what happened, can someone help me？

```
...
SKIP: track-uuid.sh
make[5]: Nothing to be done for `all'.
============================================================================
Testsuite summary for ndctl 71.1
============================================================================
# TOTAL: 26
# PASS:  1
# SKIP:  25
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
+ %ldconfig_scriptlets -n ndctl-libs
/var/tmp/rpm-tmp.Uh3XcZ: line 31: fg: no job control
error: Bad exit status from /var/tmp/rpm-tmp.Uh3XcZ (%check)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.Uh3XcZ (%check)
[root@centos7_4 ndctl]# cat -n /var/tmp/rpm-tmp.Uh3XcZ| tail -n 10
    27	  cd "/root/rpmbuild/BUILD"
    28	cd 'ndctl-71.1'
    29	make check
    30
    31	%ldconfig_scriptlets -n ndctl-libs
    32
    33	%ldconfig_scriptlets -n daxctl-libs
    34
    35
    36	exit 0[root@centos7_4 ndctl]#
```

**Comment by sscargal** [comment]
The problem is the spec file contains obsoleted scriplets for newer OS releases. [https://fedoraproject.org/wiki/Changes/Removing_ldconfig_scriptlets](https://fedoraproject.org/wiki/Changes/Removing_ldconfig_scriptlets) says "_Packagers who want to support only Fedora 28+ in their spec files can remove scriptlets entirely. For the rest, they should switch to use newly created macros._" This also applies to newer CentOS 7.x and all 8.x releases. The spec file needs to be updated to support newer OS releases.

**Comment by pokitpeng** [comment]
@sscargal Thank you, I removed the following configuration and it worked.
```bash
# file: ndctl/rhel/ndctl.spec

%ldconfig_scriptlets -n ndctl-libs
%ldconfig_scriptlets -n daxctl-libs
```
