### ISSUE TITLE
FAIL：multi-pmem

### ISSUE THREAD

**Issue by yufeixiong** [pmem/ndctl#37]
when I run command “make check”, I get the following message:
![image](https://user-images.githubusercontent.com/20283879/38007856-22073674-327e-11e8-82d6-83e8f6fead1c.png)
How do I fix it?

**Comment by stellarhopper** [comment]
Hi, all the other tests are being skipped because you likely don't have a proper 'nfit_test' kernel set up. See the instructions in the main README.md for how to do that. multi-pmem should also have been skipped, I'll look into why it fails instead.

In the meanwhile, it would help if you could paste the contents of test/test-suite.log, at least for the multi-pmem section.

Thanks,
-Vishal
