### ISSUE TITLE
ndctl doesn't catch attempts at parallel namespace operations

### ISSUE THREAD

**Issue by swdavenport** [pmem/ndctl#40]
to test how ndctl handles conflicts when multiple commands are issues to
the same device, 4 sequential reconfigure commands were issued to the same
pmem device on a AEP hardware.

this resulted in error messages from the ndctl, and the device in question
was moved to disabled state. when the device was enabled back, it was in a
mode neither it was earlier or the new one for which reconfigure command was
issued.

root# ndctl create-namespace -f -e namespace15.0 -m memory &
ndctl create-namespace -f -e namespace15.0 -m memory &ndctl create-namespace
-f -e namespace15.0 -m memory &ndctl create-namespace -f -e namespace15.0 -m
memory &
[1] 3820
[2] 3821
[3] 3822
[4] 3823

failed to reconfigure namespace: No such device or address
libndctl: ndctl_namespace_enable: libndctl: ndctl_namespace_enable:
namespace15.0: failed to enable
namespace15.0: failed to enable
libndctl: ndctl_pfn_enable: pfn15.0: failed to enable
  Error: namespace15.0: failed to enable

failed to reconfigure namespace: No such device or address
failed to reconfigure namespace: No such device or address
failed to reconfigure namespace: No such device or address

Per NVDIMM namespace specification, namespace reconfiguration must be
serialized, by driver. It looks like the ndctl <-> driver communication
should somehow catch the above scenario, and report failure as due to "device
busy"

**Comment by djbw** [comment]
The short answer is that ndctl does not lock and does not have plans to add locking. The driver *does* do locking, but not in the way, or at the level, you expect per your comment. Details below:

This behavior is an extension of the design principles that libndctl is built upon, outlined [here](https://git.kernel.org/pub/scm/linux/kernel/git/kay/libabc.git/tree/README#n66). For the same reason that there is no locking internal to the library, there is no locking between parallel utility commands.

Now to be clear, the driver does perform all of its operations internally with appropriate locks, but all that locking is designed to enforce is that one thread can update one property of one device at a time. For example if 2 ndctl threads are creating a namespace at the same time they might both discover that region0 has available capacity and both them would try to allocate that space to the namespace they are trying to create. The kernel guarantees that one of them will make the allocation and the other will see that the available capacity is now gone.

The "create-namespace -f -e namespace15.0 -m memory" command results in the follow operations with the driver:

1/ destroy namespace15.0 by
1a/ set namespace15.0 into raw mode by writing to sysfs
1b/ write zeros to the first 8k with the write system call
1c/ set its size to zero by writing to sysfs
2/ Reallocate capacity for the namespace by writing the old size to sysfs
3/ Find an idle 'pfn' device instance by walking region15's available 'pfn' devices in sysfs
4/ Assign the namespace to the 'pfn' device by writing to sysfs

Each of those sysfs operations happen atomically, but step 1b/ and step 3/ are done without driver locks. When you issue 4 of those operations in parallel all of those steps get interleaved.

A naive locking implementation would say, just have ndctl lock out all create-namespace operations against the others, but that is too coarse since it is perfectly fine to do operations on region0 and region1 in parallel for example. We could do fine grained locking within ndctl, but then the system is still exposed to a script touching sysfs directly. So the answer is, garbage in garbage out. I.e. the administrator must arrange for namespace management operations to not collide, otherwise the kernel / driver will do exactly as it is told in the order operations arrive at the driver from any thread.
