### ISSUE TITLE
ndctl "destroy-namespace -f all " does not operate correctly

### ISSUE THREAD

**Issue by swdavenport** [pmem/ndctl#41]
Tested with ndctl v60.1

ndctl destroy-namespace command does not monitor success/failure for issued
commands and reports incorrect status.  The following two scenarios
illustrate the behavior:

1) Issuing a forced destroy all namespace command reports the same number  
consistently everytime:

root# ndctl destroy-namespace -f all
destroyed 15 namespaces
root# ndctl destroy-namespace -f all
destroyed 15 namespaces

The reported count of 15 namespaces is inclusive of the default "raw" mode
namespaces that are present for each region with a size of 0 and  reporting
state disabled e.g.
  {
    "dev":"namespace12.1",
    "mode":"raw",
    "size":0,
    "uuid":"00000000-0000-0000-0000-000000000000",
    "sector_size":-1,
    "state":"disabled",
    "numa_node":1
  },

These are not destroy-able and persist on. The destroy-namespace all command
should omit such namespaces and only attempt to destroy the ones that are
user created and of a non-zero size.

2) One of the namespaces does not get destroyed despite the force flag.  This
appears to be due to the namespace having been mounted to a mount point.  The
command should return a coherent message stating that only X namespaces could
be destroyed due to one namespace being in use or something to that effect.
----------------------------
root# ndctl destroy-namespace -f all
destroyed 15 namespaces
root# ndctl list
{
  "dev":"namespace12.0",
  "mode":"memory",
  "size":132118478848,
  "uuid":"6bc4959e-e428-4a73-9480-6eac69df78c3",
  "sector_size":512,
  "blockdev":"pmem12",
  "numa_node":1
}
root# lsblk | grep pmem12
pmem12      259:2    0  123G  0 disk /olt-storage

**Comment by djbw** [comment]
Yes, this isn't the first time 'ndctl destroy-namespace' semantics have caused confusion so some fixes are warranted. Here is the explanation for the behavior you are seeing, and changes we can make going forward. The destroy-namespace command does 2 things:

1/ It "destroys", writes zeroes, do any metadata info blocks stored on the namespace. This is achieved by putting the namespace into raw mode and overwriting the first 8K of the namespace's data area. In this sense destroy-namespace operations always reports it destroyed something if these writes complete successfully. We could fix "always reports success for all namespaces" by checking if the first 8K of the namespace is already zero and skipping the namespace if it is.

2/ It attempts to return the namespace's capacity to parent region iff the namespace is in labeled mode. The labeled vs label-less distinction is a source of confusion that needs better explanation in the man pages. If you attempt to destroy a namespace that is not described by labels ndctl will write to first 8K and return the namespace back to raw mode. There is no way to delete a namespace without labels because it is 1:1 associated with a region, and regions can't be destroyed. We could make destroy-namespace less confusing by failing when the namespace object is not a candidate to be destroyed. Otherwise even with labels there will always be at least one 'seed' namespace per region. The 'seed' namespace is the kernel's mechanism for allow dynamic creation of new namespaces from available region capacity. You can read more about the mechanism [here](https://www.kernel.org/doc/Documentation/nvdimm/nvdimm.txt). We might make this clearer by having ndctl hide "seed" namespaces from the disabled namespaces listing by default.

Would these suggested changes address your concerns?

**Comment by swdavenport** [comment]
Yes, I believe so. Itemizing what you're proposing:
 
1. check, if the 1st 8K are 0s, silently ignore the namespace, do not count it
2. if the namespace is mounted, display explicit error message that says: device is busy, cannot destroy.
3. hide the 'seed' namespace from ndctl output - since it's kernel's internal mechanism, userspace doesn't have a compelling need to be constantly reminded of.  If userspace really need to know, it could consult sysfs.
4. update man page to document labeled vs label-less namespace.

That'd do it.

**Comment by swdavenport** [comment]
Cool... will check it out.

**Comment by swdavenport** [comment]
A run through with ndctl v63... still seems there is an issue.

////// 
[root@b ~]#  ndctl -v    
63
[root@b ~]# lsblk | grep pmem
pmem1       259:0    0 39.4G  0 disk /mnt/pmem1

[root@b ~]# ndctl destroy-namespace -f all
error destroying namespaces: No such device or address
destroyed 0 namespaces

[root@b ~]# lsblk | grep pmem
pmem1       259:0    0 39.4G  0 disk /mnt/pmem1

[root@b ~]# ndctl destroy-namespace  all
  Error: namespace1.0 is active, specify --force for re-configuration

error destroying namespaces: No such device or address
destroyed 0 namespaces

It seems like the issue continue to exist with ndtcl v63.  
The observation:
(1) "ndctl destroy-namespace  all",  without using the "-f or --force", the
output reported correctly that namespace is active
(2) " ndctl destroy-namespace -f all", issue remains - no warning/error is
given for the namespace being active.
