### ISSUE TITLE
Clearing devdax poison addresses

### ISSUE THREAD

**Issue by etsaur4** [pmem/ndctl#50]
When you use ndctl to inject/clear a devdax block, block = 0 refers the start of the dax device.
For instance:
/sys/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0012:00/ndbus0/region22/dax22.0/resource
and not
/sys/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0012:00/ndbus0/region22/namespace22.0/resource

There are 2 issues that occur as a result of this.
1) Minor: /sys/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0012:00/ndbus0/region22/badblocks, block 0 refers to the start of the namespace.  You cannot just plug in the block # from the badblock list to ndctl.  You have to do some math.

2) How do you clear a poison in the "metadata" region.  The area between the start of the region namespace and dax?

**Comment by djbw** [comment]
For 1. this is expected since that regionX/badblocks instance is relative to the region resource base. ndctl will translate the correct offset for badblocks relative to the namespace base when you do "ndctl list -M".

2. is arguably a gap in the current kernel enabling, but there are two ways to clear it presently:

- Disable the hosting region and use the libndctl apis to craft a clear error command to the proper physical address and then recreate the namespace.

- Reconfigure the namespace into a raw mode namespace and write to the block-device offset corresponding to the error.

The potential new enabling is to teach nd_pfn_init() to use nvdimm_write_bytes() to initialize the metadata area so that it takes care of clearing errors in the process of writing new metadata.

**Comment by etsaur4** [comment]
Thanks for the quick reply.  Using raw mode is an interesting workaround.
