### ISSUE TITLE
Force-align namespace size up?

### ISSUE THREAD

**Issue by okartau** [pmem/ndctl#79]
Background:
We use libndctl in [pmem-csi](https://github.com/intel/pmem-CSI), and we pre-check/adjust namespace size before namespace creation request to avoid some trouble(s). We have learned that alignement should be 1GB (or we hit issue like described in #76).

Some use,test cases (like [csi-sanity](https://github.com/kubernetes-csi/csi-test)) ask for arbitrary/small volume sizes, so we force-align size up to next 1GB-boundary before creation. In serving a <1GB request, pmem-csi request will thus be `size=1G align=1G`, causing libndctl failure to create a namespace, as creation will only succeed for sizes 2GB and up if alignment is 1G.
 `size=2G align=1G` will create namespace, but resulting size will be 1G as libndctl force-aligns size down (and that seems to happen even if request was already at GB-boundary, which is bit counter-intuitive?)
In general, with align=1G, the resulting size is always 1GB less than request. Such result is not suitable for pmem-csi as we can not provision volume smaller than was asked. Means, in pmem-csi we have to pre-craft our create request:
- we use libndctl option: align=1G
- size should always be at least 2GB, to avoid 1G/1G failure
- resulting size cant become smaller-than-ask by libndctl force-aligning, so we force-align(and increment if needed) size up to next 1GB before creation.

That force-aligning before calling libndctl is almost redundant repeating of the alignment part (but in upward direction).
So, what about changing libndctl to start force-aligning upwards?
Isn't it fair to expect that resulting namespace size is at least what was asked, if there is enough space available?

**Comment by djbw** [comment]
Thanks for the report. Not exactly sure what to do about it. Please read through this reply and see if any of the suggestions would help, or if I'm missing the point.

The difficult part is communicating ahead of time how much capacity is going to consumed for alignment and metadata.

Does your use case want to create namespaces in "fsdax" or "devdax" mode? Or can it use "raw" mode? I ask because the align feature is only a capability of the "*dax" modes and those require a portion of the namespace capacity to be reserved for metadata. Any metadata reservation is going to be padded up to the next 1GB boundary which is why your size=1G align=1G case fails, and why only 1G of usable capacity is yielded from a size=2G align=1G request.

Even without metadata, unless the base region is 1G aligned, you'll always lose misaligned capacity.

I believe the disconnect is that the size is specified as the capacity *before* metadata and alignment space is reserved. Would your use case be improved if there was a way to request the resulting usable capacity was no less than size X?

**Comment by okartau** [comment]
we create namespaces either in fsdax or sector mode, the fsdax being the main use case.
If resulting usable capacity would be guaranteed, it would be great as it would reduce extra
checking and pre-manipulating of size on our side.
But this is not really blocking problem, as we have already implemented draft of code which takes care of such checking and increment the size in the request.

**Comment by okartau** [comment]
Our case in pmem-csi is working with current implementation without real trouble, so we can close this, unless you prefer to keep it open for some reason.

**Comment by djbw** [comment]
Thanks for the follow up!
